apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-tolerations
  labels:
    purpose: tolerations-demo
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: tolerations-demo
      project: roboshop

  template:
    metadata:
      labels:
        purpose: tolerations-demo
        project: roboshop

    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-41-28.ec2.internal

      tolerations:
      - key: "project"
        operator: "Equal"
        value: "roboshop"
        effect: "NoSchedule"

      containers:
      - name: nginx
        image: nginx:latest